name: CircleCI Trigger Action
on: pull_request

permissions:
  contents: write
  pull-requests: write

jobs:
  trigger-circle-ci:
    if: |
      !contains(github.event.pull_request.labels.*.name, 'do-not-merge') &&
      !contains(github.event.pull_request.labels.*.name, 'wip')
    runs-on: ubuntu-latest
    name: Pull Request Triggered CircleCI
    steps:
    - uses: LedgerHQ/actions/gh-context@main
    - name: Trigger CircleCI
      id: curl-circle-ci
      uses: Open-Source-Contrib/circle-ci-trigger-action@latest
      with:
        circle_ci_token: ${{ secrets.CIRCLE_CI_TOKEN }}
        circle_ci_project_url: ${{ github.event.pull_request.head.ref }}

