name: CircleCI Trigger Action
on: pull_request

permissions:
  contents: write
  pull-requests: write

jobs:
  trigger-circle-ci:
    if: |
      !contains(github.event.pull_request.labels.*.name, 'do-not-merge') &&
      !contains(github.event.pull_request.labels.*.name, 'wip')
    runs-on: ubuntu-latest
    name: Pull Request Triggered CircleCI
    steps:
    - uses: LedgerHQ/actions/gh-context@main
    - name: Trigger CircleCI
      id: trigger-circle-ci
      uses: CircleCI-Public/trigger-circleci-pipeline-action@v1.0.5
      env:
        circle_ci_token: ${{ secrets.CIRCLE_CI_TOKEN }}

